# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '2.0'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: |
      ./api/APITest.Presentation.WebAPI/APITest.Presentation.WebAPI.csproj

- script: dotnet test './api/XUnitTest/XUnitTest.csproj' --logger trx --configuration $(buildConfiguration) --collect "Code coverage"

- task: PublishTestResults@2
  displayName: 'Publish Test results'
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: BuildQualityChecks@9
  displayName: 'Code Coverage Quality Gate'
  inputs:
    checkCoverage: true
    coverageFailOption: 'fixed'
    coverageType: 'blocks'
    coverageThreshold: '60'